baseURL = 'https://syahrul.dev/'
languageCode = 'en-us'
canonifyURLs = true
enableEmoji = true
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
googleAnalytics = 'XXXXX'
hasCJKLanguage = true
paginate = 5
publishDir = 'public'
title = "Syahrul's Personal Website"
theme = 'june'

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 1
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    style = 'vs'
    tabWidth = 4
  
[taxonomies]
  category = 'categories'

[languages]
  [languages.en]
    contentDir = 'content'
    languageName = 'English'
    weight = 1
    [languages.en.params]
    description = 'Syahrul Akbar R Personal Web'
    locale = "en_US"

    [[languages.en.menu.main]]
      name = 'HOME'
      url = '/'
      weight = 1

    [[languages.en.menu.main]]
      name = 'BLOG'
      url = '/blogs/'
      weight = 2

[author]
  Name = "Syahrul Akbar R"
  Email = 'me@syahrul.dev'

[params]
  [params.june]
    braveRewardsVerification = 'XXXXX'
    canonicalURL = 'XXXXX'
    csp = "default-src 'self' 'unsafe-inline' https:;"
    googleSiteVerification = 'XXXXX'
    monetization = '$ilp.uphold.com/XXXXX'

    [[params.june.contact]]
      Name = "Email"
      URL  = "mailto:me@syahrul.dev"

    [[params.june.contact]]
      Name = "Github"
      URL  = "https://github.com/sahruldotid"

    [[params.june.contact]]
      Name = "LinkedIn"
      URL  = "https://www.linkedin.com/in/syahrul-akbar-rohmani/"

    [[params.june.contact]]
      Name = "Twitter"
      URL  = "https://twitter.com/sahruldotid"
      
    # get from https://giscus.app/
    [params.june.giscus]
      Repo =  "sahruldotid/syahrul.dev"
      RepoID = "R_kgDOHyAXRA"
      Category = "General"
      CategoryID = "DIC_kwDOHyAXRM4CXeoP"
      Mapping = "title"
      Reaction = "1"
      Metadata = "0"
      Theme = "light"
